# Generated by Django 4.1.2 on 2022-10-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_description_alter_task_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, default='No description', max_length=120),
        ),
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
